package django_test

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/Melphins/msync/internal/adapter"
	"github.com/Melphins/msync/internal/adapter/django"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestDjangoAdapter_NameAndType(t *testing.T) {
	d := django.NewDjangoAdapter("", "")
	assert.Equal(t, adapter.AdapterTypeDjango, d.Type())
	assert.Equal(t, "Django", d.Name())
}

func TestDjangoAdapter_MigrationTable(t *testing.T) {
	d := django.NewDjangoAdapter("", "")
	assert.Equal(t, "django_migrations", d.MigrationTable())
}

func TestDjangoAdapter_IsMigrationFile(t *testing.T) {
	d := django.NewDjangoAdapter("", "")

	// Valid Django migrations (NNNN_name.py in migrations/ directory)
	assert.True(t, d.IsMigrationFile("/path/to/auth/migrations/0001_initial.py"))
	assert.True(t, d.IsMigrationFile("/path/to/users/migrations/0002_add_email.py"))
	assert.True(t, d.IsMigrationFile("migrations/0003_auto_20250101.py"))

	// Invalid files
	assert.False(t, d.IsMigrationFile("README.md"))
	assert.False(t, d.IsMigrationFile("0001_initial.py")) // Not in migrations/ dir
	assert.False(t, d.IsMigrationFile("/path/to/migrations/123_initial.py")) // Not 4 digits
	assert.False(t, d.IsMigrationFile("/path/to/auth/0001_initial.txt")) // Wrong extension
	assert.False(t, d.IsMigrationFile("/path/to/auth/notmigrations/0001_initial.py")) // Wrong parent dir name
}

func TestDjangoAdapter_ParseMigrationFile(t *testing.T) {
	tmpDir := t.TempDir()
	// migrationDir should be the parent of the app directory
	migrateDir := tmpDir
	appMigrationsDir := filepath.Join(tmpDir, "myapp", "migrations")
	os.MkdirAll(appMigrationsDir, 0755)

	migrationFile := filepath.Join(appMigrationsDir, "0001_initial.py")
	content := `# Generated by Django 5.0 on 2025-01-01

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
`
	err := os.WriteFile(migrationFile, []byte(content), 0644)
	require.NoError(t, err)

	d := django.NewDjangoAdapter("", migrateDir)
	migration, err := d.ParseMigrationFile(migrationFile)
	require.NoError(t, err)

	assert.Equal(t, "myapp:0001_initial", migration.Version)
	assert.Equal(t, "myapp.initial", migration.Name)
	assert.Equal(t, migrationFile, migration.FilePath)
	assert.Equal(t, content, migration.UpSQL)
	assert.NotEmpty(t, migration.Checksum)
	assert.False(t, migration.Timestamp.IsZero())
}

func TestDjangoAdapter_ParseMigrationFile_WithDependencies(t *testing.T) {
	tmpDir := t.TempDir()
	migrateDir := tmpDir
	appMigrationsDir := filepath.Join(tmpDir, "myapp", "migrations")
	os.MkdirAll(appMigrationsDir, 0755)

	migrationFile := filepath.Join(appMigrationsDir, "0002_add_email.py")
	content := `from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
`
	err := os.WriteFile(migrationFile, []byte(content), 0644)
	require.NoError(t, err)

	d := django.NewDjangoAdapter("", migrateDir)
	migration, err := d.ParseMigrationFile(migrationFile)
	require.NoError(t, err)

	assert.Equal(t, "myapp:0002_add_email", migration.Version)
	// The current extractDependencies is simplified - it captures the first line containing "dependencies = ["
	assert.Contains(t, migration.DownSQL, "dependencies")
	// Note: Full Python AST parsing would be needed to extract actual dependency values
}

func TestDjangoAdapter_ParseMigrationFile_InvalidFilename(t *testing.T) {
	d := django.NewDjangoAdapter("", "")

	// Invalid filename format
	migration, err := d.ParseMigrationFile("/path/to/invalid_file.py")
	assert.Error(t, err)
	assert.Equal(t, adapter.Migration{}, migration)
}

func TestDjangoAdapter_ParseMigrationFile_FileReadError(t *testing.T) {
	d := django.NewDjangoAdapter("", "/some/path")

	// Non-existent file with valid pattern
	migration, err := d.ParseMigrationFile("/nonexistent/myapp/migrations/0001_valid.py")
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "failed to read")
	assert.Equal(t, adapter.Migration{}, migration)
}

func TestDjangoAdapter_LoadMigrations(t *testing.T) {
	tmpDir := t.TempDir()

	// Create multiple apps with migrations
	apps := []string{"auth", "users", "contenttypes"}
	for _, app := range apps {
		migrateDir := filepath.Join(tmpDir, app, "migrations")
		os.MkdirAll(migrateDir, 0755)

		migrations := []struct {
			filename string
			content  string
		}{
			{
				fmt.Sprintf("0001_initial_%s.py", app),
				fmt.Sprintf("class Migration(migrations.Migration):\n    dependencies = []\n    operations = []\n# %s initial", app),
			},
			{
				fmt.Sprintf("0002_update_%s.py", app),
				fmt.Sprintf("class Migration(migrations.Migration):\n    dependencies = [('%s', '0001_initial_%s')]\n    operations = []\n# %s update", app, app, app),
			},
		}

		for _, m := range migrations {
			filePath := filepath.Join(migrateDir, m.filename)
			os.WriteFile(filePath, []byte(m.content), 0644)
		}
	}

	d := django.NewDjangoAdapter("", tmpDir)
	err := d.LoadMigrations()
	require.NoError(t, err)

	migs, err := d.GetMigrations()
	require.NoError(t, err)

	// Should load 6 migrations (3 apps * 2 migrations each)
	assert.Len(t, migs, 6)

	// Create a map of versions for easy lookup
	versionMap := make(map[string]string)
	for _, m := range migs {
		versionMap[m.Version] = m.Name
	}

	// Check that all expected versions exist
	expectedVersions := []string{
		"auth:0001_initial_auth",
		"auth:0002_update_auth",
		"users:0001_initial_users",
		"users:0002_update_users",
		"contenttypes:0001_initial_contenttypes",
		"contenttypes:0002_update_contenttypes",
	}
	for _, ver := range expectedVersions {
		_, exists := versionMap[ver]
		assert.True(t, exists, "expected version %s to exist", ver)
	}
}

func TestDjangoAdapter_LoadMigrations_SortedByAppAndNumber(t *testing.T) {
	tmpDir := t.TempDir()

	// Create one app with migrations out of order
	migrateDir := filepath.Join(tmpDir, "myapp", "migrations")
	os.MkdirAll(migrateDir, 0755)

	migrations := []struct {
		filename string
		content  string
	}{
		{"0003_third.py", "class Migration(migrations.Migration):\n    dependencies = []\n    operations = []"},
		{"0001_first.py", "class Migration(migrations.Migration):\n    dependencies = []\n    operations = []"},
		{"0002_second.py", "class Migration(migrations.Migration):\n    dependencies = []\n    operations = []"},
	}

	for _, m := range migrations {
		filePath := filepath.Join(migrateDir, m.filename)
		os.WriteFile(filePath, []byte(m.content), 0644)
	}

	d := django.NewDjangoAdapter("", tmpDir)
	err := d.LoadMigrations()
	require.NoError(t, err)

	migs, _ := d.GetMigrations()

	// Should be sorted by number
	assert.Equal(t, "myapp:0001_first", migs[0].Version)
	assert.Equal(t, "myapp:0002_second", migs[1].Version)
	assert.Equal(t, "myapp:0003_third", migs[2].Version)
}

func TestDjangoAdapter_LoadMigrations_DirectoryDoesNotExist(t *testing.T) {
	d := django.NewDjangoAdapter("", "/nonexistent")
	err := d.LoadMigrations()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "does not exist")
}

func TestDjangoAdapter_LoadMigrations_MigrationDirNotSet(t *testing.T) {
	d := django.NewDjangoAdapter("", "")
	err := d.LoadMigrations()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "migration directory not set")
}

func TestDjangoAdapter_FindMigrationByVersion(t *testing.T) {
	tmpDir := t.TempDir()
	migrateDir := filepath.Join(tmpDir, "myapp", "migrations")
	os.MkdirAll(migrateDir, 0755)

	// Create test migrations
	for i := 1; i <= 3; i++ {
		filename := fmt.Sprintf("%04d_test_%d.py", i, i)
		filePath := filepath.Join(migrateDir, filename)
		content := fmt.Sprintf("class Migration(migrations.Migration):\n    dependencies = []\n    operations = []\n# Test %d", i)
		os.WriteFile(filePath, []byte(content), 0644)
	}

	d := django.NewDjangoAdapter("", tmpDir)
	err := d.LoadMigrations()
	require.NoError(t, err)

	// Test finding existing migration
	mig, err := d.FindMigrationByVersion("myapp:0001_test_1")
	require.NoError(t, err)
	assert.Equal(t, "myapp:0001_test_1", mig.Version)

	// Test finding another existing migration
	mig, err = d.FindMigrationByVersion("myapp:0003_test_3")
	require.NoError(t, err)
	assert.Equal(t, "myapp:0003_test_3", mig.Version)

	// Test finding non-existent migration
	_, err = d.FindMigrationByVersion("nonexistent:0001_test")
	assert.Error(t, err)
	assert.Equal(t, adapter.ErrMigrationNotFound, err)
}

func TestDjangoAdapter_Diff_NoDifferences(t *testing.T) {
	current := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "email", Type: "varchar(255)"},
				},
				PrimaryKey: []string{"id"},
			},
			"django_migrations": {
				Name: "django_migrations",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "app", Type: "varchar(255)"},
					{Name: "name", Type: "varchar(255)"},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	target := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "email", Type: "varchar(255)"},
				},
				PrimaryKey: []string{"id"},
			},
			"django_migrations": {
				Name: "django_migrations",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "app", Type: "varchar(255)"},
					{Name: "name", Type: "varchar(255)"},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	d := &django.DjangoAdapter{}
	diff, err := d.Diff(current, target)
	require.NoError(t, err)

	assert.Len(t, diff.TablesAdded, 0)
	assert.Len(t, diff.TablesRemoved, 0)
	assert.Len(t, diff.ColumnsAdded, 0)
	assert.Len(t, diff.ColumnsRemoved, 0)
	assert.Len(t, diff.ColumnsModified, 0)
}

func TestDjangoAdapter_Diff_ColumnAdded(t *testing.T) {
	current := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "email", Type: "varchar(255)"},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	target := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "email", Type: "varchar(255)"},
					{Name: "role", Type: "varchar(50)", Nullable: true},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	d := &django.DjangoAdapter{}
	diff, err := d.Diff(current, target)
	require.NoError(t, err)

	assert.Len(t, diff.ColumnsAdded, 1)
	assert.Equal(t, "role", diff.ColumnsAdded[0].Column)
	assert.Equal(t, "varchar(50)", diff.ColumnsAdded[0].NewType)
	assert.True(t, diff.ColumnsAdded[0].NewNullable)
}

func TestDjangoAdapter_Diff_ColumnRemoved(t *testing.T) {
	current := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "email", Type: "varchar(255)"},
					{Name: "deprecated_field", Type: "varchar(50)"},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	target := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "email", Type: "varchar(255)"},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	d := &django.DjangoAdapter{}
	diff, err := d.Diff(current, target)
	require.NoError(t, err)

	assert.Len(t, diff.ColumnsRemoved, 1)
	assert.Equal(t, "deprecated_field", diff.ColumnsRemoved[0].Column)
	assert.Equal(t, "varchar(50)", diff.ColumnsRemoved[0].OldType)
}

func TestDjangoAdapter_Diff_ColumnModified(t *testing.T) {
	current := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "email", Type: "varchar(100)", Nullable: true},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	target := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "email", Type: "varchar(255)", Nullable: false},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	d := &django.DjangoAdapter{}
	diff, err := d.Diff(current, target)
	require.NoError(t, err)

	assert.Len(t, diff.ColumnsModified, 1)
	assert.Equal(t, "email", diff.ColumnsModified[0].Column)
	assert.Equal(t, "varchar(100)", diff.ColumnsModified[0].OldType)
	assert.Equal(t, "varchar(255)", diff.ColumnsModified[0].NewType)
	assert.True(t, diff.ColumnsModified[0].OldNullable)
	assert.False(t, diff.ColumnsModified[0].NewNullable)
}

func TestDjangoAdapter_Diff_TableAdded(t *testing.T) {
	current := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{{Name: "id", Type: "integer"}},
			},
		},
	}

	target := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{{Name: "id", Type: "integer"}},
			},
			"posts": {
				Name: "posts",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "title", Type: "varchar(255)"},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	d := &django.DjangoAdapter{}
	diff, err := d.Diff(current, target)
	require.NoError(t, err)

	assert.Len(t, diff.TablesAdded, 1)
	assert.Contains(t, diff.TablesAdded, "posts")
}

func TestDjangoAdapter_Diff_TableRemoved(t *testing.T) {
	current := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{{Name: "id", Type: "integer"}},
			},
			"posts": {
				Name: "posts",
				Columns: []adapter.SchemaColumn{{Name: "id", Type: "integer"}},
			},
		},
	}

	target := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{{Name: "id", Type: "integer"}},
			},
		},
	}

	d := &django.DjangoAdapter{}
	diff, err := d.Diff(current, target)
	require.NoError(t, err)

	assert.Len(t, diff.TablesRemoved, 1)
	assert.Contains(t, diff.TablesRemoved, "posts")
}

func TestDjangoAdapter_Diff_Complex(t *testing.T) {
	current := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "email", Type: "varchar(100)"},
					{Name: "old_field", Type: "varchar(50)"},
				},
				PrimaryKey: []string{"id"},
			},
			"posts": {
				Name: "posts",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "title", Type: "varchar(255)"},
				},
				PrimaryKey: []string{"id"},
			},
			"django_migrations": {
				Name: "django_migrations",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "app", Type: "varchar(255)"},
					{Name: "name", Type: "varchar(255)"},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	target := &adapter.Schema{
		Tables: map[string]adapter.SchemaTable{
			"users": {
				Name: "users",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "email", Type: "varchar(255)"},         // Modified
					{Name: "role", Type: "varchar(50)", Nullable: true}, // Added
				},
				PrimaryKey: []string{"id"},
			},
			"comments": {
				Name: "comments",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "body", Type: "text"},
				},
				PrimaryKey: []string{"id"},
			},
			"django_migrations": {
				Name: "django_migrations",
				Columns: []adapter.SchemaColumn{
					{Name: "id", Type: "integer", IsPrimaryKey: true},
					{Name: "app", Type: "varchar(255)"},
					{Name: "name", Type: "varchar(255)"},
				},
				PrimaryKey: []string{"id"},
			},
		},
	}

	d := &django.DjangoAdapter{}
	diff, err := d.Diff(current, target)
	require.NoError(t, err)

	// Tables: comments added, posts removed
	assert.Len(t, diff.TablesAdded, 1)
	assert.Contains(t, diff.TablesAdded, "comments")
	assert.Len(t, diff.TablesRemoved, 1)
	assert.Contains(t, diff.TablesRemoved, "posts")

	// Columns in users table
	assert.Len(t, diff.ColumnsAdded, 1)
	assert.Equal(t, "role", diff.ColumnsAdded[0].Column)
	assert.Len(t, diff.ColumnsRemoved, 1)
	assert.Equal(t, "old_field", diff.ColumnsRemoved[0].Column)
	assert.Len(t, diff.ColumnsModified, 1)
	assert.Equal(t, "email", diff.ColumnsModified[0].Column)
	assert.Equal(t, "varchar(100)", diff.ColumnsModified[0].OldType)
	assert.Equal(t, "varchar(255)", diff.ColumnsModified[0].NewType)
}

func TestDjangoAdapter_simpleChecksum(t *testing.T) {
	// Test that checksum is deterministic
	tmpDir := t.TempDir()
	migrateDir := filepath.Join(tmpDir, "myapp", "migrations")
	os.MkdirAll(migrateDir, 0755)

	data1 := []byte("class Migration(migrations.Migration):\n    dependencies = []\n    operations = []")
	data2 := []byte("class Migration(migrations.Migration):\n    dependencies = []\n    operations = []")
	data3 := []byte("class Migration(migrations.Migration):\n    dependencies = []\n    operations = [some difference]")

	file1 := filepath.Join(migrateDir, "0001_test1.py")
	file2 := filepath.Join(migrateDir, "0002_test2.py")
	file3 := filepath.Join(migrateDir, "0003_test3.py")

	os.WriteFile(file1, data1, 0644)
	os.WriteFile(file2, data2, 0644)
	os.WriteFile(file3, data3, 0644)

	d := django.NewDjangoAdapter("", tmpDir)

	mig1, _ := d.ParseMigrationFile(file1)
	mig2, _ := d.ParseMigrationFile(file2)
	mig3, _ := d.ParseMigrationFile(file3)

	// Same content should produce same checksum
	assert.Equal(t, mig1.Checksum, mig2.Checksum)
	// Different content should produce different checksum
	assert.NotEqual(t, mig1.Checksum, mig3.Checksum)
}

func TestDjangoAdapter_extractMigrationNumber(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected int
	}{
		{"0001_initial", "0001_initial", 1},
		{"0002_add_field", "0002_add_field", 2},
		{"0123_test", "0123_test", 123},
		{"0001", "0001", 1},
		{"no_number", "no_number", 0},
		{"", "", 0},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := extractMigrationNumber(tt.input)
			assert.Equal(t, tt.expected, result, "extractMigrationNumber(%s) = %d, want %d", tt.input, result, tt.expected)
		})
	}
}

// extractMigrationNumber is exported for testing
func extractMigrationNumber(name string) int {
	var num int
	for _, r := range name {
		if r >= '0' && r <= '9' {
			num = num*10 + int(r-'0')
		} else {
			break
		}
	}
	return num
}
