version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "bazzi24"
    assignees:
      - "bazzi24"
    labels:
      - "dependencies"
      - "gomod"
